export const ROUTES = {
  HOME: '/',
  ACCESO: '/acceso',
  PANEL: '/panel',
  ESCANEAR: '/escanear',
  ADMIN: '/admin',
  ADMIN_QR: '/admin/qr',
  ADMIN_USUARIOS: '/admin/usuarios',
  ADMIN_REPORTES: '/admin/reportes',
  ADMIN_UBICACIONES: '/admin/ubicaciones',
  ADMIN_TURNOS: '/admin/turnos',
  ADMIN_AUSENCIAS: '/admin/ausencias',
  ADMIN_LEGAJOS: '/admin/legajos',
  ADMIN_RECIBOS: '/admin/recibos',
  ADMIN_VACACIONES: '/admin/vacaciones',
  ADMIN_EVALUACIONES: '/admin/evaluaciones',
  EMPLEADO: '/empleado',
  HISTORIAL: '/historial',
  PERFIL: '/perfil',
  PERFIL_DOCUMENTOS: '/perfil/documentos',
  AUSENCIAS: '/ausencias',
  RECIBOS: '/recibos',
  VACACIONES: '/vacaciones',
  EVALUACIONES: '/evaluaciones',
} as const;
